### ISSUE TITLE
Write `etl/reassign_redcap_prod_per_project_line_item.R`

### ISSUE THREAD

**Issue by pbchase** [ctsit/rcc.billing#32]
Write `etl/reassign_redcap_prod_per_project_line_item.R`. After invoices are sent, investigators will report that some projects do not belong to them. CTS-IT will change the ownership of these projects to a new owner. In other cases, the customer will change the ownership of a project themselves. CTS-IT will create a report of differences in project ownership and investigators of each unpaid, invoiced project. CTS-IT will update its tables and tell CSBT about the change. 

- [ ] Call `get_unpaid_redcap_prod_per_project_line_items` and write the result to the dataframe `sent_line_items`
- [x] Query `redcap_entity_project_ownership` with 
```r
filter(
  project_id %in% sent_line_items$project_id &
)
```
- [x] Join the result above with `sent_line_items` then filter for revised PI info and generate the revised data as shown below and save the result in `reassigned_line_items` (consider using `csbt_column_names$ctsi` to help with the select step.  See issues #35 ):
```r
filter(
    gatorlink  != username |
    pi_email != email |
    pi_first_name != firstname |
    pi_last_name != lastname
  ) %>%
mutate(
    gatorlink  = username,
    pi_email = email,
    pi_first_name = firstname,
    pi_last_name = lastname,
    reason = "PI reassigned",
    updated = get_script_runtime()
) %>%
select(
  service_type_code,
  service_instance_id,
  ctsi_study_id,
  name_of_service,
  other_system_invoicing_comments,
  cost_of_service,
  qty_provided,
  amount_due,
  fiscal_year,
  month_invoiced,
  pi_last_name,
  pi_first_name,
  pi_email,
  gatorlink,
  reason,
  status,
  created,
  updated
)
```
- [x] Prepare a dataset, `reassigned_line_items_for_csbt` using `transform_invoice_line_items_for_csbt()` from Issue #33 and to transform `reassigned_line_items` created above. i.e.
```r
reassigned_line_items_for_csbt <- transform_invoice_line_items_for_csbt(reassigned_line_items)
```
- [x] Write `reassigned_line_items_for_csbt` to a file `reassigned_line_items.csv` in a temp location.
- [x] Draft the communications records using the function created in issue #31 
```r
updates_reassigned_line_item_communications <- draft_communication_record_from_line_item(reassigned_line_items)
```
- [x] Prepare an email from the recipient and to the sender attach the temp file updates_to_invoice_line_item.csv.
- [x] Update `invoice_line_item` with `reassigned_line_items`
- [x] Update `invoice_line_item_communications` with `updates_reassigned_line_item_communications`
- [x] Send the email
- [x] Terminate logging
- [x] disconnect from the DB
- [ ] CTS-IT will send this dataset monthly as part of the monthly new billing.
